###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    db:
      container_name: soccerdome-db
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      volumes:
        - ./soccerdome.sql:/application/soccerdome.sql
      environment:
        MYSQL_ROOT_PASSWORD: soccerdome
        MYSQL_DATABASE: Soccerdome
        MYSQL_USER: root
        MYSQL_PASSWORD: soccerdome
      ports:
       - "3306:3306"

    adminer:
      container_name: soccerdome-adminer
      depends_on:
        - db
      image: adminer:latest
      ports:
        - 3050:8080
      restart: always

    webserver:
      image: nginx:alpine
      container_name: soccerdome-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8050:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: soccerdome-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

volumes:
    db_data: